### ISSUE TITLE
 [Curseforge Fabric] Please add the 'Fabric' category to the modpage

### ISSUE THREAD

**Issue by Umimoto-Shimao** [TelepathicGrunt/WorldBlender-Fabric#1]
Hi! Fabric users searching Curseforge by filtering with the 'Fabric' category cannot see your mod at this time. Please add it to your modpage found here -> https://www.curseforge.com/minecraft/mc-mods/world-blender-fabric

**Comment by TelepathicGrunt** [comment]
I actually ran out of tags as mod pages can only have 1 main tag and 4 subtags. The file itself is already taged for fabric modloader which curseforge should've made show up in fabric searched but noooo.

I had replaced one of the sub tags with fabric for now but I would prefer to have all the worldgen tags as that best describes my mod
