### ISSUE TITLE
Portal will not open

### ISSUE THREAD

**Issue by TrueCP6** [TelepathicGrunt/WorldBlender-Fabric#5]
In the config I set the required amount of items to 8 and I have 8 single chests in a 2x2x2 cube with a unique block in each but upon sneak right clicking with a nether star, nothing happens. I watched the mod spotlight on the curseforge page and I have done exactly what he has but I can not get it to work. Teleporting directly into the dimension with `/execute in world_blender:world_blender` works as expected.

**Comment by TelepathicGrunt** [comment]
Can you provide the config file so I can see what settings it has? It would be in the config folder above the mods folder

**Comment by TrueCP6** [comment]
[Here it is](https://github.com/TelepathicGrunt/WorldBlender-Fabric/files/5610696/world_blender.json5.txt). I had to change the file extension to `.txt` because github doesn't allow uploading `.json5`s.

**Comment by TelepathicGrunt** [comment]
Hmm. It is working for me with the configs you have. This is with me using v1.0.10 of World Blender. Works in creative and survival. 

Just to make sure, you are using v1.0.10 of would blender right? And you are crouching when you click the use button when holding a Nether Star in your main hand? Even if the chests had invalid stuff in them, a message should pop up saying what is wrong with the chest contents.

If you are on latest version and crouch clicking didn't work, then I suspect it is a mod conflict. If so, can you provide me a list of mods you are using or your zipped up mod folder? Very interesting tho...
![image](https://user-images.githubusercontent.com/40846040/100517869-fceb5c00-315b-11eb-8a20-73774020d22a.png)
![image](https://user-images.githubusercontent.com/40846040/100517873-0674c400-315c-11eb-99f2-78f9d3c0421c.png)

**Comment by TrueCP6** [comment]
I am using v1.0.10 and the only mods I have are Fabric API and Mod Menu. When crouch right clicking with a nether star in the main hand there is no message and nothing happens.
![2020-11-28_16 39 01](https://user-images.githubusercontent.com/39642832/100518133-62f5d480-3198-11eb-9c5c-31defd6a1fa2.png)

**Comment by TelepathicGrunt** [comment]
can you provide your latest.log file? That way I can see the version of everything and can try and see if I can reproduce the issue

**Comment by TrueCP6** [comment]
[latest.log](https://github.com/TelepathicGrunt/WorldBlender-Fabric/files/5610734/latest.log)

**Comment by TelepathicGrunt** [comment]
Ok I reproduced the issue. wtf is going on lmao

**Comment by TelepathicGrunt** [comment]
v1.0.11 should have this now fixed! thank you for letting me know about the bug!
https://www.curseforge.com/minecraft/mc-mods/world-blender-fabric/files/3125528
